{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.obscuria",
    "module": "hekate",
    "version": "1.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hekate-1.0.52.jar",
          "url": "hekate-1.0.52.jar",
          "size": 17236,
          "sha512": "38fc8d3e6c907e50a4a5c1e00e8e563df79d45f0a5e64287c52c2a2e7f02a1c58b9f5633f7d33cdc929ade1d1f4dce2701a0905a4ded11583e4878cd3b24a2dc",
          "sha256": "e9cb243963a651a632a467fa8630a14694f00c6dddc5e6d7356dd2ebdc72e572",
          "sha1": "50b59e965de05a04be9bbe6d8d6f96078f068815",
          "md5": "f60d348553f129c9bd638737f5fea0cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.darkhax.curseforgegradle",
          "module": "CurseForgeGradle",
          "version": {
            "requires": "1.1.28"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "hekate-1.0.52.jar",
          "url": "hekate-1.0.52.jar",
          "size": 17236,
          "sha512": "38fc8d3e6c907e50a4a5c1e00e8e563df79d45f0a5e64287c52c2a2e7f02a1c58b9f5633f7d33cdc929ade1d1f4dce2701a0905a4ded11583e4878cd3b24a2dc",
          "sha256": "e9cb243963a651a632a467fa8630a14694f00c6dddc5e6d7356dd2ebdc72e572",
          "sha1": "50b59e965de05a04be9bbe6d8d6f96078f068815",
          "md5": "f60d348553f129c9bd638737f5fea0cc"
        }
      ]
    }
  ]
}
